### ISSUE TITLE
Create Github repo!

### ISSUE THREAD

**Issue by alexpandel** [18F/cms-oversight#1]
**Goal:** start working in the open!

**This task is done when:**
- [x] we've created a repo
- [x] we've transferred over the relevant tasks to the tracker [here](https://github.com/18F/cms-oversight/projects/1) 
- [x] we've shared this with Nick & Liz!

**Comment by alexpandel** [comment]
@amyashida feel free to pull in any other tasks that you think belong in here, otherwise I think we have a good start in here! And then maybe we can share with Nick & Liz tomorrow during coworking...
