### ISSUE TITLE
Write brief findings report from recent SO testing

### ISSUE THREAD

**Issue by alexpandel** [18F/cms-oversight#2]
**Goal:** document our findings & resulting product decisions from our last two rounds of SO workshops testing out V1 of the MES Health Tracker

**This task is done when:**
- [x] we've written up a brief (1-2 pg) summary of our findings & next steps
- [x] we've published it to [the wiki](https://github.com/18F/cms-oversight/wiki)

- [x]  we have thumbs up from Nick and Liz on what to publish

**Reference material:** [synthesis Mural](https://app.mural.co/t/gsa6/m/gsa6/1587403703080/632a579cdfde9bf8d3aab77078aa19260e4d983b)

**Comment by alexpandel** [comment]
@amyashida I'm gonna assign this one to you for now since I didn't get to it this afternoon, but I think most of the meat of it is in the Mural anyway!

**Comment by alexpandel** [comment]
@amyashida, I'm working on an initial draft [in here](https://docs.google.com/document/d/1UCySumqG_FO0gXgAHbFHFwjDdNk4bAhN_myJlL4dBC0/edit) to make co-writing/editing in the early stages a little easier, but once we're ready for Nick & Liz's, feedback we can transfer it over to the wiki.

**Comment by nickarrow** [comment]
👍
