### ISSUE TITLE
Scope out content strategy need on project

### ISSUE THREAD

**Issue by alexpandel** [18F/cms-oversight#25]
**Who is the user?** 
18F team

**What will this help them do?**
Help us understand how best to tackle the content strategy issues related to this project, and if we need to bring a content strategist onboard to help.

**When is it needed?**
Not time sensitive, but the earlier, the better

**What steps are needed to make it a reality?**
- [x] decide who's help would be most useful 
- [x] schedule time with them
- [x] have meeting
- [ ] spin up microrequest for content strategy help

**Comment by alexpandel** [comment]
@amyashida if this seems right to you, I'm going to close this for now as we wait to see what comes of #33... if we _do_ get more funding, I'd like to turn this into a full-time staffing request, and if we don't, _then_ we can look into a microrequest. That sound right to you? 

If not, feel free to reopen this or open a new issue for a spinning up a microrequest!
