### ISSUE TITLE
Flesh out the rest of the product framing in the wiki

### ISSUE THREAD

**Issue by alexpandel** [18F/cms-oversight#6]
**Goal:** the Github wiki becomes the single source of truth for product framing info

**This task will be done when:**
- [x] we've pulled in goals (likely from [here](https://docs.google.com/document/d/1vEK53XkkEWRQPkBjVc12rTOReUko-zFVtDokBDoziGw/edit#heading=h.ilrlu2ma29jm))
- [x] we've pulled in key user needs & pain points (likely from [here](https://docs.google.com/document/d/1s3AnASrqGtJgkN-zp1YGifj-kOJ0gaoSpFQE84MeS2U/edit#heading=h.ne07rod7vbdo) and [here](https://docs.google.com/document/d/1pYW5-JAHEOrAmPQRzUPcpxvbvVVvbGg7jXMBcHYfmzg/edit#heading=h.ne07rod7vbdo)?)
- [x] we've pilled in risks (from [here](https://docs.google.com/document/d/1s3AnASrqGtJgkN-zp1YGifj-kOJ0gaoSpFQE84MeS2U/edit#heading=h.tmz78hlu6znv))
- [ ] [MAYBE:] we've pulled in key scenarios (from [here](https://docs.google.com/document/d/1g09JGJcaX9qwh4-JjH5XJDodogndXag2KK27HwXDppI/edit#heading=h.g5xckcc4gzvn))?
