### ISSUE TITLE
Add other relevant info to the wiki

### ISSUE THREAD

**Issue by alexpandel** [18F/cms-oversight#7]
**Goal:** anything that _can_ be public, _is_ public (and easily findable) in the wiki.

**Possible things to include:**
- [x] product hypotheses (from [here](https://docs.google.com/document/d/1g09JGJcaX9qwh4-JjH5XJDodogndXag2KK27HwXDppI/edit#heading=h.2qdxb5wcpp79)?)
- [ ] user pain points & needs? (from [here](https://docs.google.com/document/d/1g09JGJcaX9qwh4-JjH5XJDodogndXag2KK27HwXDppI/edit#heading=h.2qdxb5wcpp79)?)
- [ ] a page with our biweekly ships (a la [this one](https://github.com/18F/eligibility-rules-service/wiki/Weekly-recaps#phase-3---october-1-2018-to-present))?
- [ ] link to Rosetta Stone?
- [ ] link to Medicaid IT ecosystem map?

**Comment by alexpandel** [comment]
FYI @amyashida, in prepping for #30, I ended up trying to centralize our hypotheses [into one place in the wiki](https://github.com/18F/cms-oversight/wiki/product-hypotheses). Part of my thinking was that it could be cool if, going forward (and maybe retroactively [with our first research round](https://github.com/18F/cms-oversight/wiki/Research-and-Prototyping-Findings) on the tracker), we experimented with spelling out specifically _which_ of our hypotheses we're testing in a given research round ([like this](https://github.com/18F/cms-oversight/wiki/MES-Health-Rubric-Testing-Plan#hypotheses-were-testing)), and then, depending on our conclusions from the research, could go back to [the hypotheses page](https://github.com/18F/cms-oversight/wiki/Product-hypotheses) and update those hypotheses based on our new knowledge...

But! This was a late-night idea, so I'd love a gut check from you on whether this feels useful or overly complicated. If it _does_ feel useful, a few next steps might be:

- [ ] updating [our prior research summary](https://github.com/18F/cms-oversight/wiki/Research-and-Prototyping-Findings) to include the specific hypotheses we were testing in that round, which would probably require:
  - [ ] actually writing some hypotheses related to the investment size representation, MDBT, and any other hypotheses we were testing that aren't already captured in [this section](https://github.com/18F/cms-oversight/wiki/Product-hypotheses#hypotheses-about-the-mes-health-tracker) of the hypotheses page.
- [ ] checking back in [the tracker section of the hypotheses page](https://github.com/18F/cms-oversight/wiki/Product-hypotheses#hypotheses-about-the-mes-health-tracker) to see if we want to update any of those prior hypotheses based on our learnings from that research round (fwiw, I pulled the hypotheses that are currently in there from [this old doc](https://docs.google.com/document/d/1g09JGJcaX9qwh4-JjH5XJDodogndXag2KK27HwXDppI/edit#)).

So, feel free to edit/change around any and all of this, or otherwise let me know what you think!

**Comment by alexpandel** [comment]
oh, two other heads ups: 
- I removed the "consistency/confidence/capturing" thing from the _test plan_, since that didn't quite feel like the right place for it. I expect it belongs somewhere in the framing doc, but late-night brain couldn't figure out where exactly, so let's add it back in when we figure out the right spot for it.
- I also removed the placeholder-y "training materials" page altogether — I figure we can add it back once we're ready to put in some actual content.
